# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/MainWindowUI.ui'
#
# Created: Mon Sep  9 11:33:16 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(340, 430)
        self.ctrlMainWindowWidget = QtGui.QWidget(MainWindow)
        self.ctrlMainWindowWidget.setObjectName(_fromUtf8("ctrlMainWindowWidget"))
        self.ctrlMainWindowWidgetLayout = QtGui.QGridLayout(self.ctrlMainWindowWidget)
        self.ctrlMainWindowWidgetLayout.setObjectName(_fromUtf8("ctrlMainWindowWidgetLayout"))
        self.ctrlMainWindowLayout = QtGui.QVBoxLayout()
        self.ctrlMainWindowLayout.setObjectName(_fromUtf8("ctrlMainWindowLayout"))
        self.ctrlDeviceStatus = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlDeviceStatus.setObjectName(_fromUtf8("ctrlDeviceStatus"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ctrlDeviceStatus)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ctrlDeviceStatusLayout = QtGui.QHBoxLayout()
        self.ctrlDeviceStatusLayout.setObjectName(_fromUtf8("ctrlDeviceStatusLayout"))
        self.ctrlKeyboardOutput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlKeyboardOutput.setEnabled(False)
        self.ctrlKeyboardOutput.setObjectName(_fromUtf8("ctrlKeyboardOutput"))
        self.ctrlDeviceStatusLayout.addWidget(self.ctrlKeyboardOutput)
        self.ctrlKeypadInput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlKeypadInput.setEnabled(False)
        self.ctrlKeypadInput.setObjectName(_fromUtf8("ctrlKeypadInput"))
        self.ctrlDeviceStatusLayout.addWidget(self.ctrlKeypadInput)
        self.ctrlMidiInput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlMidiInput.setEnabled(False)
        self.ctrlMidiInput.setObjectName(_fromUtf8("ctrlMidiInput"))
        self.ctrlDeviceStatusLayout.addWidget(self.ctrlMidiInput)
        self.gridLayout_4.addLayout(self.ctrlDeviceStatusLayout, 0, 0, 1, 1)
        self.ctrlMainWindowLayout.addWidget(self.ctrlDeviceStatus)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ctrlMainWindowLayout.addItem(spacerItem)
        self.ctrlMainWindowLayout1 = QtGui.QHBoxLayout()
        self.ctrlMainWindowLayout1.setObjectName(_fromUtf8("ctrlMainWindowLayout1"))
        self.ctrlAccidental = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlAccidental.setCheckable(False)
        self.ctrlAccidental.setObjectName(_fromUtf8("ctrlAccidental"))
        self.gridLayout = QtGui.QGridLayout(self.ctrlAccidental)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ctrlAccidentalLayout = QtGui.QVBoxLayout()
        self.ctrlAccidentalLayout.setObjectName(_fromUtf8("ctrlAccidentalLayout"))
        self.ctrlAccidentalNone = QtGui.QRadioButton(self.ctrlAccidental)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlAccidentalNone.setFont(font)
        self.ctrlAccidentalNone.setChecked(True)
        self.ctrlAccidentalNone.setObjectName(_fromUtf8("ctrlAccidentalNone"))
        self.ctrlAccidentalLayout.addWidget(self.ctrlAccidentalNone)
        self.ctrlAccidentalFlat = QtGui.QRadioButton(self.ctrlAccidental)
        self.ctrlAccidentalFlat.setObjectName(_fromUtf8("ctrlAccidentalFlat"))
        self.ctrlAccidentalLayout.addWidget(self.ctrlAccidentalFlat)
        self.ctrlAccidentalSharp = QtGui.QRadioButton(self.ctrlAccidental)
        self.ctrlAccidentalSharp.setObjectName(_fromUtf8("ctrlAccidentalSharp"))
        self.ctrlAccidentalLayout.addWidget(self.ctrlAccidentalSharp)
        self.gridLayout.addLayout(self.ctrlAccidentalLayout, 0, 0, 1, 1)
        self.ctrlMainWindowLayout1.addWidget(self.ctrlAccidental)
        self.ctrlOctave = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlOctave.setCheckable(False)
        self.ctrlOctave.setObjectName(_fromUtf8("ctrlOctave"))
        self.gridLayout_2 = QtGui.QGridLayout(self.ctrlOctave)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ctrlOctaveLayout = QtGui.QVBoxLayout()
        self.ctrlOctaveLayout.setObjectName(_fromUtf8("ctrlOctaveLayout"))
        self.ctrlOctaveNone = QtGui.QRadioButton(self.ctrlOctave)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlOctaveNone.setFont(font)
        self.ctrlOctaveNone.setChecked(True)
        self.ctrlOctaveNone.setObjectName(_fromUtf8("ctrlOctaveNone"))
        self.ctrlOctaveLayout.addWidget(self.ctrlOctaveNone)
        self.ctrlOctaveDown = QtGui.QRadioButton(self.ctrlOctave)
        self.ctrlOctaveDown.setObjectName(_fromUtf8("ctrlOctaveDown"))
        self.ctrlOctaveLayout.addWidget(self.ctrlOctaveDown)
        self.ctrlOctaveUp = QtGui.QRadioButton(self.ctrlOctave)
        self.ctrlOctaveUp.setObjectName(_fromUtf8("ctrlOctaveUp"))
        self.ctrlOctaveLayout.addWidget(self.ctrlOctaveUp)
        self.gridLayout_2.addLayout(self.ctrlOctaveLayout, 0, 0, 1, 1)
        self.ctrlMainWindowLayout1.addWidget(self.ctrlOctave)
        self.ctrlMainWindowLayout.addLayout(self.ctrlMainWindowLayout1)
        self.ctrlDuration = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlDuration.setCheckable(False)
        self.ctrlDuration.setObjectName(_fromUtf8("ctrlDuration"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ctrlDuration)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ctrlDurationLayout = QtGui.QVBoxLayout()
        self.ctrlDurationLayout.setObjectName(_fromUtf8("ctrlDurationLayout"))
        self.ctrlDurationNone = QtGui.QRadioButton(self.ctrlDuration)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlDurationNone.setFont(font)
        self.ctrlDurationNone.setChecked(True)
        self.ctrlDurationNone.setObjectName(_fromUtf8("ctrlDurationNone"))
        self.ctrlDurationLayout.addWidget(self.ctrlDurationNone)
        self.ctrlDurationLayout1 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout1.setObjectName(_fromUtf8("ctrlDurationLayout1"))
        self.ctrlDuration1 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration1.setObjectName(_fromUtf8("ctrlDuration1"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDuration1)
        self.ctrlDurationBreve = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDurationBreve.setObjectName(_fromUtf8("ctrlDurationBreve"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDurationBreve)
        self.ctrlDurationLonga = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDurationLonga.setObjectName(_fromUtf8("ctrlDurationLonga"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDurationLonga)
        self.ctrlDurationLayout.addLayout(self.ctrlDurationLayout1)
        self.ctrlDurationLayout2 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout2.setObjectName(_fromUtf8("ctrlDurationLayout2"))
        self.ctrlDuration8 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration8.setObjectName(_fromUtf8("ctrlDuration8"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration8)
        self.ctrlDuration4 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration4.setObjectName(_fromUtf8("ctrlDuration4"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration4)
        self.ctrlDuration2 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration2.setObjectName(_fromUtf8("ctrlDuration2"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration2)
        self.ctrlDurationLayout.addLayout(self.ctrlDurationLayout2)
        self.ctrlDurationLayout3 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout3.setObjectName(_fromUtf8("ctrlDurationLayout3"))
        self.ctrlDuration64 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration64.setObjectName(_fromUtf8("ctrlDuration64"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration64)
        self.ctrlDuration32 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration32.setObjectName(_fromUtf8("ctrlDuration32"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration32)
        self.ctrlDuration16 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration16.setObjectName(_fromUtf8("ctrlDuration16"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration16)
        self.ctrlDurationLayout.addLayout(self.ctrlDurationLayout3)
        spacerItem1 = QtGui.QSpacerItem(0, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.ctrlDurationLayout.addItem(spacerItem1)
        self.ctrlDurationDot = QtGui.QCheckBox(self.ctrlDuration)
        self.ctrlDurationDot.setObjectName(_fromUtf8("ctrlDurationDot"))
        self.ctrlDurationLayout.addWidget(self.ctrlDurationDot)
        self.gridLayout_3.addLayout(self.ctrlDurationLayout, 1, 0, 1, 1)
        self.ctrlMainWindowLayout.addWidget(self.ctrlDuration)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ctrlMainWindowLayout.addItem(spacerItem2)
        self.ctrlEnable = QtGui.QPushButton(self.ctrlMainWindowWidget)
        self.ctrlEnable.setEnabled(True)
        self.ctrlEnable.setMinimumSize(QtCore.QSize(0, 50))
        self.ctrlEnable.setCheckable(True)
        self.ctrlEnable.setChecked(False)
        self.ctrlEnable.setObjectName(_fromUtf8("ctrlEnable"))
        self.ctrlMainWindowLayout.addWidget(self.ctrlEnable)
        self.ctrlMainWindowWidgetLayout.addLayout(self.ctrlMainWindowLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.ctrlMainWindowWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ctrlAccidentalNone, self.ctrlAccidentalFlat)
        MainWindow.setTabOrder(self.ctrlAccidentalFlat, self.ctrlAccidentalSharp)
        MainWindow.setTabOrder(self.ctrlAccidentalSharp, self.ctrlOctaveNone)
        MainWindow.setTabOrder(self.ctrlOctaveNone, self.ctrlOctaveDown)
        MainWindow.setTabOrder(self.ctrlOctaveDown, self.ctrlOctaveUp)
        MainWindow.setTabOrder(self.ctrlOctaveUp, self.ctrlDurationNone)
        MainWindow.setTabOrder(self.ctrlDurationNone, self.ctrlDuration64)
        MainWindow.setTabOrder(self.ctrlDuration64, self.ctrlDuration32)
        MainWindow.setTabOrder(self.ctrlDuration32, self.ctrlDuration16)
        MainWindow.setTabOrder(self.ctrlDuration16, self.ctrlDuration8)
        MainWindow.setTabOrder(self.ctrlDuration8, self.ctrlDuration4)
        MainWindow.setTabOrder(self.ctrlDuration4, self.ctrlDuration2)
        MainWindow.setTabOrder(self.ctrlDuration2, self.ctrlDuration1)
        MainWindow.setTabOrder(self.ctrlDuration1, self.ctrlDurationBreve)
        MainWindow.setTabOrder(self.ctrlDurationBreve, self.ctrlDurationLonga)
        MainWindow.setTabOrder(self.ctrlDurationLonga, self.ctrlDurationDot)
        MainWindow.setTabOrder(self.ctrlDurationDot, self.ctrlEnable)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LilyFrog Control", None))
        self.ctrlDeviceStatus.setTitle(_translate("MainWindow", "Device status", None))
        self.ctrlKeyboardOutput.setText(_translate("MainWindow", "Keyboard OUT", None))
        self.ctrlKeypadInput.setText(_translate("MainWindow", "Keypad IN", None))
        self.ctrlMidiInput.setText(_translate("MainWindow", "MIDI IN", None))
        self.ctrlAccidental.setTitle(_translate("MainWindow", "Accidental change", None))
        self.ctrlAccidentalNone.setText(_translate("MainWindow", "None", None))
        self.ctrlAccidentalFlat.setText(_translate("MainWindow", "Flat", None))
        self.ctrlAccidentalSharp.setText(_translate("MainWindow", "Sharp", None))
        self.ctrlOctave.setTitle(_translate("MainWindow", "Octave change", None))
        self.ctrlOctaveNone.setText(_translate("MainWindow", "None", None))
        self.ctrlOctaveDown.setText(_translate("MainWindow", "Down", None))
        self.ctrlOctaveUp.setText(_translate("MainWindow", "Up", None))
        self.ctrlDuration.setTitle(_translate("MainWindow", "Duration change", None))
        self.ctrlDurationNone.setText(_translate("MainWindow", "None", None))
        self.ctrlDuration1.setText(_translate("MainWindow", "Whole", None))
        self.ctrlDurationBreve.setText(_translate("MainWindow", "Breve", None))
        self.ctrlDurationLonga.setText(_translate("MainWindow", "Longa", None))
        self.ctrlDuration8.setText(_translate("MainWindow", "Eighth", None))
        self.ctrlDuration4.setText(_translate("MainWindow", "Quarter", None))
        self.ctrlDuration2.setText(_translate("MainWindow", "Half", None))
        self.ctrlDuration64.setText(_translate("MainWindow", "64th", None))
        self.ctrlDuration32.setText(_translate("MainWindow", "32nd", None))
        self.ctrlDuration16.setText(_translate("MainWindow", "16th", None))
        self.ctrlDurationDot.setText(_translate("MainWindow", "Dotted", None))
        self.ctrlEnable.setText(_translate("MainWindow", "Enable LilyFrog", None))

