# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/MainWindowUI.ui'
#
# Created: Sun Sep  8 22:26:18 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(300, 370)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setChecked(True)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.verticalLayout_4.addWidget(self.radioButton_16)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.horizontalLayout_3.addWidget(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.horizontalLayout_3.addWidget(self.radioButton_15)
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.horizontalLayout_3.addWidget(self.radioButton_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.horizontalLayout_2.addWidget(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.horizontalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.horizontalLayout_2.addWidget(self.radioButton_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.horizontalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.horizontalLayout.addWidget(self.radioButton_8)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.horizontalLayout.addWidget(self.radioButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(0, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_4.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.radioButton_5)
        MainWindow.setTabOrder(self.radioButton_5, self.radioButton_6)
        MainWindow.setTabOrder(self.radioButton_6, self.radioButton_16)
        MainWindow.setTabOrder(self.radioButton_16, self.radioButton_7)
        MainWindow.setTabOrder(self.radioButton_7, self.radioButton_8)
        MainWindow.setTabOrder(self.radioButton_8, self.radioButton_9)
        MainWindow.setTabOrder(self.radioButton_9, self.radioButton_10)
        MainWindow.setTabOrder(self.radioButton_10, self.radioButton_11)
        MainWindow.setTabOrder(self.radioButton_11, self.radioButton_12)
        MainWindow.setTabOrder(self.radioButton_12, self.radioButton_14)
        MainWindow.setTabOrder(self.radioButton_14, self.radioButton_15)
        MainWindow.setTabOrder(self.radioButton_15, self.radioButton_13)
        MainWindow.setTabOrder(self.radioButton_13, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LilyFrog Control", None))
        self.groupBox.setTitle(_translate("MainWindow", "Accidental change", None))
        self.radioButton_3.setText(_translate("MainWindow", "None", None))
        self.radioButton.setText(_translate("MainWindow", "Flat", None))
        self.radioButton_2.setText(_translate("MainWindow", "Sharp", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Octave change", None))
        self.radioButton_4.setText(_translate("MainWindow", "None", None))
        self.radioButton_5.setText(_translate("MainWindow", "Down", None))
        self.radioButton_6.setText(_translate("MainWindow", "Up", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Duration change", None))
        self.radioButton_16.setText(_translate("MainWindow", "None", None))
        self.radioButton_14.setText(_translate("MainWindow", "Whole", None))
        self.radioButton_15.setText(_translate("MainWindow", "Breve", None))
        self.radioButton_13.setText(_translate("MainWindow", "Longa", None))
        self.radioButton_10.setText(_translate("MainWindow", "Eighth", None))
        self.radioButton_11.setText(_translate("MainWindow", "Quarter", None))
        self.radioButton_12.setText(_translate("MainWindow", "Half", None))
        self.radioButton_7.setText(_translate("MainWindow", "64th", None))
        self.radioButton_8.setText(_translate("MainWindow", "32nd", None))
        self.radioButton_9.setText(_translate("MainWindow", "16th", None))
        self.checkBox.setText(_translate("MainWindow", "Dotted", None))
        self.pushButton.setText(_translate("MainWindow", "Enable LilyFrog", None))

