# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/MainWindowUI.ui'
#
# Created: Wed Sep 11 16:06:09 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(400, 500)
        self.ctrlMainWindowWidget = QtGui.QWidget(MainWindow)
        self.ctrlMainWindowWidget.setObjectName(_fromUtf8("ctrlMainWindowWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ctrlMainWindowWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ctrlDeviceStatus = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlDeviceStatus.setObjectName(_fromUtf8("ctrlDeviceStatus"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.ctrlDeviceStatus)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ctrlKeyboardOutput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlKeyboardOutput.setEnabled(False)
        self.ctrlKeyboardOutput.setObjectName(_fromUtf8("ctrlKeyboardOutput"))
        self.horizontalLayout.addWidget(self.ctrlKeyboardOutput)
        self.ctrlKeypadInput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlKeypadInput.setEnabled(False)
        self.ctrlKeypadInput.setObjectName(_fromUtf8("ctrlKeypadInput"))
        self.horizontalLayout.addWidget(self.ctrlKeypadInput)
        self.ctrlMidiInput = QtGui.QCheckBox(self.ctrlDeviceStatus)
        self.ctrlMidiInput.setEnabled(False)
        self.ctrlMidiInput.setObjectName(_fromUtf8("ctrlMidiInput"))
        self.horizontalLayout.addWidget(self.ctrlMidiInput)
        self.verticalLayout_4.addWidget(self.ctrlDeviceStatus)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.ctrlDefaultAccidental = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlDefaultAccidental.setObjectName(_fromUtf8("ctrlDefaultAccidental"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ctrlDefaultAccidental)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ctrlDefaultAccidentalFlat = QtGui.QRadioButton(self.ctrlDefaultAccidental)
        self.ctrlDefaultAccidentalFlat.setChecked(True)
        self.ctrlDefaultAccidentalFlat.setObjectName(_fromUtf8("ctrlDefaultAccidentalFlat"))
        self.horizontalLayout_2.addWidget(self.ctrlDefaultAccidentalFlat)
        self.ctrlDefaultAccidentalSharp = QtGui.QRadioButton(self.ctrlDefaultAccidental)
        self.ctrlDefaultAccidentalSharp.setObjectName(_fromUtf8("ctrlDefaultAccidentalSharp"))
        self.horizontalLayout_2.addWidget(self.ctrlDefaultAccidentalSharp)
        self.verticalLayout_4.addWidget(self.ctrlDefaultAccidental)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.ctrlAccidentalOctaveLayout = QtGui.QHBoxLayout()
        self.ctrlAccidentalOctaveLayout.setObjectName(_fromUtf8("ctrlAccidentalOctaveLayout"))
        self.ctrlAccidental = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlAccidental.setCheckable(False)
        self.ctrlAccidental.setObjectName(_fromUtf8("ctrlAccidental"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ctrlAccidental)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ctrlAccidentalNone = QtGui.QRadioButton(self.ctrlAccidental)
        self.ctrlAccidentalNone.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlAccidentalNone.setFont(font)
        self.ctrlAccidentalNone.setChecked(True)
        self.ctrlAccidentalNone.setObjectName(_fromUtf8("ctrlAccidentalNone"))
        self.verticalLayout_2.addWidget(self.ctrlAccidentalNone)
        self.ctrlAccidentalFlat = QtGui.QRadioButton(self.ctrlAccidental)
        self.ctrlAccidentalFlat.setEnabled(False)
        self.ctrlAccidentalFlat.setObjectName(_fromUtf8("ctrlAccidentalFlat"))
        self.verticalLayout_2.addWidget(self.ctrlAccidentalFlat)
        self.ctrlAccidentalSharp = QtGui.QRadioButton(self.ctrlAccidental)
        self.ctrlAccidentalSharp.setEnabled(False)
        self.ctrlAccidentalSharp.setObjectName(_fromUtf8("ctrlAccidentalSharp"))
        self.verticalLayout_2.addWidget(self.ctrlAccidentalSharp)
        self.ctrlAccidentalOctaveLayout.addWidget(self.ctrlAccidental)
        self.ctrlOctave = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlOctave.setCheckable(False)
        self.ctrlOctave.setObjectName(_fromUtf8("ctrlOctave"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ctrlOctave)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ctrlOctaveNone = QtGui.QRadioButton(self.ctrlOctave)
        self.ctrlOctaveNone.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlOctaveNone.setFont(font)
        self.ctrlOctaveNone.setChecked(True)
        self.ctrlOctaveNone.setObjectName(_fromUtf8("ctrlOctaveNone"))
        self.verticalLayout.addWidget(self.ctrlOctaveNone)
        self.ctrlOctaveDown = QtGui.QRadioButton(self.ctrlOctave)
        self.ctrlOctaveDown.setEnabled(False)
        self.ctrlOctaveDown.setObjectName(_fromUtf8("ctrlOctaveDown"))
        self.verticalLayout.addWidget(self.ctrlOctaveDown)
        self.ctrlOctaveUp = QtGui.QRadioButton(self.ctrlOctave)
        self.ctrlOctaveUp.setEnabled(False)
        self.ctrlOctaveUp.setObjectName(_fromUtf8("ctrlOctaveUp"))
        self.verticalLayout.addWidget(self.ctrlOctaveUp)
        self.ctrlAccidentalOctaveLayout.addWidget(self.ctrlOctave)
        self.verticalLayout_4.addLayout(self.ctrlAccidentalOctaveLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.ctrlDuration = QtGui.QGroupBox(self.ctrlMainWindowWidget)
        self.ctrlDuration.setCheckable(False)
        self.ctrlDuration.setObjectName(_fromUtf8("ctrlDuration"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.ctrlDuration)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.ctrlDurationNone = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDurationNone.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ctrlDurationNone.setFont(font)
        self.ctrlDurationNone.setChecked(True)
        self.ctrlDurationNone.setObjectName(_fromUtf8("ctrlDurationNone"))
        self.verticalLayout_3.addWidget(self.ctrlDurationNone)
        self.ctrlDurationLayout1 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout1.setObjectName(_fromUtf8("ctrlDurationLayout1"))
        self.ctrlDuration1 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration1.setEnabled(False)
        self.ctrlDuration1.setObjectName(_fromUtf8("ctrlDuration1"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDuration1)
        self.ctrlDurationBreve = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDurationBreve.setEnabled(False)
        self.ctrlDurationBreve.setObjectName(_fromUtf8("ctrlDurationBreve"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDurationBreve)
        self.ctrlDurationLonga = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDurationLonga.setEnabled(False)
        self.ctrlDurationLonga.setObjectName(_fromUtf8("ctrlDurationLonga"))
        self.ctrlDurationLayout1.addWidget(self.ctrlDurationLonga)
        self.verticalLayout_3.addLayout(self.ctrlDurationLayout1)
        self.ctrlDurationLayout2 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout2.setObjectName(_fromUtf8("ctrlDurationLayout2"))
        self.ctrlDuration8 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration8.setEnabled(False)
        self.ctrlDuration8.setObjectName(_fromUtf8("ctrlDuration8"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration8)
        self.ctrlDuration4 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration4.setEnabled(False)
        self.ctrlDuration4.setObjectName(_fromUtf8("ctrlDuration4"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration4)
        self.ctrlDuration2 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration2.setEnabled(False)
        self.ctrlDuration2.setObjectName(_fromUtf8("ctrlDuration2"))
        self.ctrlDurationLayout2.addWidget(self.ctrlDuration2)
        self.verticalLayout_3.addLayout(self.ctrlDurationLayout2)
        self.ctrlDurationLayout3 = QtGui.QHBoxLayout()
        self.ctrlDurationLayout3.setObjectName(_fromUtf8("ctrlDurationLayout3"))
        self.ctrlDuration64 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration64.setEnabled(False)
        self.ctrlDuration64.setObjectName(_fromUtf8("ctrlDuration64"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration64)
        self.ctrlDuration32 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration32.setEnabled(False)
        self.ctrlDuration32.setObjectName(_fromUtf8("ctrlDuration32"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration32)
        self.ctrlDuration16 = QtGui.QRadioButton(self.ctrlDuration)
        self.ctrlDuration16.setEnabled(False)
        self.ctrlDuration16.setObjectName(_fromUtf8("ctrlDuration16"))
        self.ctrlDurationLayout3.addWidget(self.ctrlDuration16)
        self.verticalLayout_3.addLayout(self.ctrlDurationLayout3)
        spacerItem3 = QtGui.QSpacerItem(0, 9, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.ctrlDurationDot = QtGui.QCheckBox(self.ctrlDuration)
        self.ctrlDurationDot.setEnabled(False)
        self.ctrlDurationDot.setObjectName(_fromUtf8("ctrlDurationDot"))
        self.verticalLayout_3.addWidget(self.ctrlDurationDot)
        self.verticalLayout_4.addWidget(self.ctrlDuration)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.ctrlEnable = QtGui.QPushButton(self.ctrlMainWindowWidget)
        self.ctrlEnable.setEnabled(True)
        self.ctrlEnable.setMinimumSize(QtCore.QSize(0, 50))
        self.ctrlEnable.setCheckable(True)
        self.ctrlEnable.setChecked(False)
        self.ctrlEnable.setObjectName(_fromUtf8("ctrlEnable"))
        self.verticalLayout_4.addWidget(self.ctrlEnable)
        MainWindow.setCentralWidget(self.ctrlMainWindowWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ctrlEnable, self.ctrlKeyboardOutput)
        MainWindow.setTabOrder(self.ctrlKeyboardOutput, self.ctrlKeypadInput)
        MainWindow.setTabOrder(self.ctrlKeypadInput, self.ctrlMidiInput)
        MainWindow.setTabOrder(self.ctrlMidiInput, self.ctrlDefaultAccidentalFlat)
        MainWindow.setTabOrder(self.ctrlDefaultAccidentalFlat, self.ctrlDefaultAccidentalSharp)
        MainWindow.setTabOrder(self.ctrlDefaultAccidentalSharp, self.ctrlAccidentalNone)
        MainWindow.setTabOrder(self.ctrlAccidentalNone, self.ctrlAccidentalFlat)
        MainWindow.setTabOrder(self.ctrlAccidentalFlat, self.ctrlAccidentalSharp)
        MainWindow.setTabOrder(self.ctrlAccidentalSharp, self.ctrlOctaveNone)
        MainWindow.setTabOrder(self.ctrlOctaveNone, self.ctrlOctaveDown)
        MainWindow.setTabOrder(self.ctrlOctaveDown, self.ctrlOctaveUp)
        MainWindow.setTabOrder(self.ctrlOctaveUp, self.ctrlDurationNone)
        MainWindow.setTabOrder(self.ctrlDurationNone, self.ctrlDurationLonga)
        MainWindow.setTabOrder(self.ctrlDurationLonga, self.ctrlDurationBreve)
        MainWindow.setTabOrder(self.ctrlDurationBreve, self.ctrlDuration1)
        MainWindow.setTabOrder(self.ctrlDuration1, self.ctrlDuration2)
        MainWindow.setTabOrder(self.ctrlDuration2, self.ctrlDuration4)
        MainWindow.setTabOrder(self.ctrlDuration4, self.ctrlDuration8)
        MainWindow.setTabOrder(self.ctrlDuration8, self.ctrlDuration16)
        MainWindow.setTabOrder(self.ctrlDuration16, self.ctrlDuration32)
        MainWindow.setTabOrder(self.ctrlDuration32, self.ctrlDuration64)
        MainWindow.setTabOrder(self.ctrlDuration64, self.ctrlDurationDot)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LilyFrog", None))
        self.ctrlDeviceStatus.setTitle(_translate("MainWindow", "Device connection status", None))
        self.ctrlKeyboardOutput.setText(_translate("MainWindow", "Keyboard OUT", None))
        self.ctrlKeypadInput.setText(_translate("MainWindow", "Keypad IN", None))
        self.ctrlMidiInput.setText(_translate("MainWindow", "MIDI IN", None))
        self.ctrlDefaultAccidental.setTitle(_translate("MainWindow", "Default black key behavior", None))
        self.ctrlDefaultAccidentalFlat.setText(_translate("MainWindow", "Flat", None))
        self.ctrlDefaultAccidentalSharp.setText(_translate("MainWindow", "Sharp", None))
        self.ctrlAccidental.setTitle(_translate("MainWindow", "Accidental change", None))
        self.ctrlAccidentalNone.setText(_translate("MainWindow", "None", None))
        self.ctrlAccidentalFlat.setText(_translate("MainWindow", "Flat", None))
        self.ctrlAccidentalSharp.setText(_translate("MainWindow", "Sharp", None))
        self.ctrlOctave.setTitle(_translate("MainWindow", "Octave change", None))
        self.ctrlOctaveNone.setText(_translate("MainWindow", "None", None))
        self.ctrlOctaveDown.setText(_translate("MainWindow", "Down", None))
        self.ctrlOctaveUp.setText(_translate("MainWindow", "Up", None))
        self.ctrlDuration.setTitle(_translate("MainWindow", "Duration change", None))
        self.ctrlDurationNone.setText(_translate("MainWindow", "None", None))
        self.ctrlDuration1.setText(_translate("MainWindow", "Whole", None))
        self.ctrlDurationBreve.setText(_translate("MainWindow", "Breve", None))
        self.ctrlDurationLonga.setText(_translate("MainWindow", "Longa", None))
        self.ctrlDuration8.setText(_translate("MainWindow", "Eighth", None))
        self.ctrlDuration4.setText(_translate("MainWindow", "Quarter", None))
        self.ctrlDuration2.setText(_translate("MainWindow", "Half", None))
        self.ctrlDuration64.setText(_translate("MainWindow", "64th", None))
        self.ctrlDuration32.setText(_translate("MainWindow", "32nd", None))
        self.ctrlDuration16.setText(_translate("MainWindow", "16th", None))
        self.ctrlDurationDot.setText(_translate("MainWindow", "Dotted", None))
        self.ctrlEnable.setText(_translate("MainWindow", "Enable LilyFrog", None))

